- name: 'prep proxmox hosts for automation'
  hosts: 'proxmox'
  vars_prompt:
  - name: PV_password
    prompt: "Proxmox Password"
    private: yes
  - name: VM_name
    prompt: "VM name"
    private: no
  - name: VM_network
    prompt: "Network bridge (default vmbr1 (behind opnsense) "
    private: no
    default: vmbr1
  - name: VM_IP
    prompt: "VM IP (opnsense is dhcp) "
    private: no
    default: none
  - name: VM_sockets
    prompt: "VM socket/s"
    private: no
    default: 1
  - name: VM_cores
    prompt: "VM core/s"
    private: no
    default: 1
  - name: VM_memory
    prompt: "VM RAM Memory (MB)"
    private: no
    default: 1024
  - name: VM_INCREASE_DISK
    prompt: "Increase virtio0 disk (20 GB) in"
    private: no
    default: 0
  - name: PV_node
    prompt: "Migrate Virtual Machine to (ignore)"
    private: no
    default: none
  user: root
  gather_facts: false
  roles:
    - { role: proxmox_deploy, default_proxmox_node: proxmox }
